// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrmWatcher) DeepCopyInto(out *KrmWatcher) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrmWatcher.
func (in *KrmWatcher) DeepCopy() *KrmWatcher {
	if in == nil {
		return nil
	}
	out := new(KrmWatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrmWatcher) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrmWatcherList) DeepCopyInto(out *KrmWatcherList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KrmWatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrmWatcherList.
func (in *KrmWatcherList) DeepCopy() *KrmWatcherList {
	if in == nil {
		return nil
	}
	out := new(KrmWatcherList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrmWatcherList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrmWatcherSpec) DeepCopyInto(out *KrmWatcherSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrmWatcherSpec.
func (in *KrmWatcherSpec) DeepCopy() *KrmWatcherSpec {
	if in == nil {
		return nil
	}
	out := new(KrmWatcherSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrmWatcherStatus) DeepCopyInto(out *KrmWatcherStatus) {
	*out = *in
	in.StreamerStatus.DeepCopyInto(&out.StreamerStatus)
	in.VerifierStatus.DeepCopyInto(&out.VerifierStatus)
	in.AggregatorStatus.DeepCopyInto(&out.AggregatorStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrmWatcherStatus.
func (in *KrmWatcherStatus) DeepCopy() *KrmWatcherStatus {
	if in == nil {
		return nil
	}
	out := new(KrmWatcherStatus)
	in.DeepCopyInto(out)
	return out
}
