// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrmRedis) DeepCopyInto(out *KrmRedis) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrmRedis.
func (in *KrmRedis) DeepCopy() *KrmRedis {
	if in == nil {
		return nil
	}
	out := new(KrmRedis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrmRedis) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrmRedisList) DeepCopyInto(out *KrmRedisList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KrmRedis, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrmRedisList.
func (in *KrmRedisList) DeepCopy() *KrmRedisList {
	if in == nil {
		return nil
	}
	out := new(KrmRedisList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrmRedisList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrmRedisSpec) DeepCopyInto(out *KrmRedisSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.StorageSpec.DeepCopyInto(&out.StorageSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrmRedisSpec.
func (in *KrmRedisSpec) DeepCopy() *KrmRedisSpec {
	if in == nil {
		return nil
	}
	out := new(KrmRedisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrmRedisStatus) DeepCopyInto(out *KrmRedisStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrmRedisStatus.
func (in *KrmRedisStatus) DeepCopy() *KrmRedisStatus {
	if in == nil {
		return nil
	}
	out := new(KrmRedisStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrmStorageSpec) DeepCopyInto(out *KrmStorageSpec) {
	*out = *in
	in.HostPath.DeepCopyInto(&out.HostPath)
	out.Storage = in.Storage.DeepCopy()
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]corev1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrmStorageSpec.
func (in *KrmStorageSpec) DeepCopy() *KrmStorageSpec {
	if in == nil {
		return nil
	}
	out := new(KrmStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrmWatcher) DeepCopyInto(out *KrmWatcher) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrmWatcher.
func (in *KrmWatcher) DeepCopy() *KrmWatcher {
	if in == nil {
		return nil
	}
	out := new(KrmWatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrmWatcher) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrmWatcherList) DeepCopyInto(out *KrmWatcherList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KrmWatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrmWatcherList.
func (in *KrmWatcherList) DeepCopy() *KrmWatcherList {
	if in == nil {
		return nil
	}
	out := new(KrmWatcherList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrmWatcherList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrmWatcherSpec) DeepCopyInto(out *KrmWatcherSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrmWatcherSpec.
func (in *KrmWatcherSpec) DeepCopy() *KrmWatcherSpec {
	if in == nil {
		return nil
	}
	out := new(KrmWatcherSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrmWatcherStatus) DeepCopyInto(out *KrmWatcherStatus) {
	*out = *in
	in.StreamerStatus.DeepCopyInto(&out.StreamerStatus)
	in.VerifierStatus.DeepCopyInto(&out.VerifierStatus)
	in.AggregatorStatus.DeepCopyInto(&out.AggregatorStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrmWatcherStatus.
func (in *KrmWatcherStatus) DeepCopy() *KrmWatcherStatus {
	if in == nil {
		return nil
	}
	out := new(KrmWatcherStatus)
	in.DeepCopyInto(out)
	return out
}
