cluster:
  name: cluster
  endpoint: ""
  token: ""
  
redis:
  name: krm-redis
  service: krm-redis.default.svc
  port: "6379"
  password: password
  image: frodenas/redis
  imagePullPolicy: Always
  volume:
    size: 10Gi
    accessMode: ReadWriteMany

influxdb:
  name: krm-influxdb
  service: krm-influxdb.default.svc
  port: "8086"
  username: krm-influxdb
  password: password
  database: krm-influxdb
  image: influxdb:latest
  imagePullPolicy: Always
  volume:
    size: 10Gi
    accessMode: ReadWriteMany

chronograf:
  name: krm-chronograf
  port: "8888"
  image: chronograf
  imagePullPolicy: Always
  ingressHost: krm-chronograf

app:
  image: docker-registry:5000/krm-app:latest
  imagePullPolicy: Always

  api:
    name: krm-api
    port: "8003"
    ingressHost: krm-api

  store_stream:
    name: krm-store-stream

  podWatcher: krm-pod-watcher
  pvcWatcher: krm-pvc-watcher
  nodeWatcher: krm-node-watcher
  serviceWatcher: krm-service-watcher
  ingressWatcher: krm-ingress-watcher
  deploymentWatcher: krm-deployment-watcher

  apiResources:
    # NOTE: Select from the following api resources to watch
    pod:
      env: pod
      enabled: True
    pvc:
      env: pvc
      enabled: True
    node:
      env: node
      enabled: True
    service:
      env: service
      enabled: True
    ingress:
      env: ingress
      enabled: True
    deployment:
      env: deployment
      enabled: True

  streamer:
    name: streamer
    args: ['app_streamer.py']

  verifier:
    name: verifier
    args: ['app_verifier.py']
    wait: 15

  aggregator:
    name: aggregator
    args: ['app_aggregator.py']
    wait: 2
